### ISSUE TITLE
Use CSS to frame images

### ISSUE THREAD

**Issue by talha131** [Pelican-Elegant/elegant#39]
Perhaps

``` css
#article img {
    padding:5px;
    border:1px solid #969696;
    background-color:#e1e1e1;

}
```
